apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
spec:
  type: NodePort # defines the type of service
  selector:
    app: nginx
  ports:
    - port: 80 # service is exposed on this port inside the cluster
      targetPort: 80 # the port on the container inside the pod where traffic should be directed to
      nodePort: 30001 # service is mapped to this port on the node
