apiVersion: apps/v1
kind: Deployment
metadata:
  name: second-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-tech201-app
  template:
    metadata:
      labels:
        app: nginx-tech201-app
    spec:
      containers:
      - name: nginx
        image: daraymonsta/tech201-nginx-auto:v1
        ports:
        - containerPort: 80
