apiVersion: v1
kind: Service
metadata:
  name: mongo-svc
spec:
  selector:
    app: mongo
  ports:
    - port: 27017 # service is exposed on this port inside the cluster
      targetPort: 27017 # the port on the container inside the pod where traffic should be directed to