apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
spec:
  capacity:
    storage: 100Mi  # equivalent to 100MB 
  accessModes:
    - ReadWriteOnce  # the volume will be mounted as read-write by a single node (my local machine)
  hostPath:
    path: /data/db  # path on the host (docker desktop) where the data will be stored
  persistentVolumeReclaimPolicy: Retain  # keeps the data after the PV is deleted
