---
- name: Setup Node.js 20 and Install App Dependencies
  hosts: farah-ec2-instance-app
  become: true

  tasks:
    - name: Install Node.js and npm
      apt:
        name: nodejs
        state: present
        update_cache: yes

    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600  # one hour in seconds, so it will run update after 1 hour

    - name: Upgrade all packages
      apt:
        upgrade: dist  # upgrades everything on the distro

    - name: Remove existing app directory if it exists
      file:
        path: "/home/ubuntu/app"
        state: absent

    - name: Clone the repository (dev branch)
      git:
        repo: "https://github.com/farahc123/tech501-sparta-app-CICD.git"
        dest: "/home/ubuntu/repo"
        version: "dev"

    - name: Navigate to the app folder and install dependencies and start the app
      shell: |
        cd /home/ubuntu/repo/nodejs20-sparta-test-app/app
        npm install
        npm start
# on the EC2 this is called 