---
- name: Setup Node.js 20 and Install App Dependencies
  hosts: farah-ec2-instance-app
  become: true

  tasks:

    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600  # one hour in seconds, so it will run update after 1 hour

    - name: Upgrade all packages
      apt:
        upgrade: dist  # upgrades everything on the distro

    - name: Install Node.js 20
      shell: |
        DEBIAN_FRONTEND=noninteractive curl -fsSL https://deb.nodesource.com/setup_20.x | bash - && \
        DEBIAN_FRONTEND=noninteractive apt-get install -y nodejs
      args:
        creates: /usr/bin/node  # Prevents the task from running if Node.js is already installed

    - name: Remove existing app directory if it exists
      file:
        path: "/home/ubuntu/app"
        state: absent

    - name: Clone the repository (dev branch)
      git:
        repo: "https://github.com/farahc123/tech501-sparta-app-CICD.git"
        dest: "/home/ubuntu/repo"
        version: "dev"

    - name: Navigate to the app folder and install dependencies and start the app
      shell: |
        cd /home/ubuntu/repo/nodejs20-sparta-test-app/app
        npm install
        npm start