services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"  # Forwards external traffic to nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro  # Uses custom nginx.config file
    depends_on:
      - app
  app:
    build:
      context: .
      args:
        - DB_HOSTS=mongodb://mongo_db:27017/posts  # Defines DB_HOST before build
    container_name: sparta-test-app
    ports:
      - "3000:3000"  # Exposes Node.js directly
    depends_on:
      mongo_db:
        condition: service_healthy  # Ensures MongoDB is fully ready before app starts
    environment:
      - DB_HOST=mongodb://mongo_db:27017/posts
  
  mongo_db:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017" 
    volumes:
      - mongo_db_data:/data/db  # Persists MongoDB data
    healthcheck:  # Adds health check to ensure MongoDB is fully ready before app starts
      test: ["CMD", "mongosh", "--eval", "db.runCommand({ ping: 1 })"]
      interval: 10s
      retries: 5
      start_period: 20s
  
volumes:
  mongo_db_data:
 
 