apiVersion: apps/v1 
kind: Deployment # defines the type of kubernetes object
metadata:
  name: sparta-app-deployment # deployment name
spec: # specifies the desired state of the deployment
  replicas: 3 # number of identical pods to be run
  selector:
    matchLabels:
      app: sparta-app # tells the deployment which pods to manage by matching the labels/tags
  template: # contains the pod template, to be used when creating new pods
    metadata:
      labels:
        app: sparta-app # label/tag for pod, this must match the replica selector label
    spec: # specifies the desired state of the pod
      containers:
      - name: sparta-app # container name
        image: farahc123/project8-app-db-method2 # image to be pulled from docker hub
        resources:
            requests:
              cpu: "100m"      # a minimum of 100 millicores or 0.1 CPU core will be assigned to the container
              memory: "128Mi"   # a minimum of 128 MiB of memory will be assigned to the container
            limits:
              cpu: "200m"       # a maximum of 200 millicores or 0.2 CPU core can be used by the container
              memory: "256Mi" # a maximum of 256 MiB of memory can be used by the container
        ports:
        - containerPort: 3000 # for the NodeJS app
        env: # sets environment variables 
        - name: DB_HOST # sets the key of the environment variable to be used to connect the database later on
          value: "mongodb://mongo-svc:27017/posts" # sets the value of the environment variable to be used to connect to the database later on
