apiVersion: v1
kind: Service
metadata:
  name: sparta-svc
spec:
  type: NodePort # defines the type of service
  selector:
    app: sparta-app
  ports:
    - port: 3000 # service is exposed on this port inside the cluster
      targetPort: 3000 # the port on the container inside the pod where traffic should be directed to
      nodePort: 30002 # service is mapped to this port on the node
